### ISSUE TITLE
Problem integration jqcloud with react

### ISSUE THREAD

**Issue by Vitorgus** [XanderDwyl/react-jqcloud#2]
Hello! Sorry for contacting you this way, but you didn't have any public email in your profile. I have a little question, if you don't mind answering it. I've been using your react wrap for jqcloud in a program, but unfortunately, the cloud doesn't change size if the window resizes. No big deal, I though, I just need to destroy and rebuild the cloud on componentDidUpdate() or something, and that means ditching your wrapper and working directly with jqcloud. But I haven't been able to get jquery and jcloud to work with react. I've searched everywhere, and nothing worked. How did you managed to get both working with react to create the wrapper?

**Comment by XanderDwyl** [comment]
Hi @Vitorgus it's been awhile working with github repo cause I've been into bitbucket with my client using it. yeah thanks for contacting me if you need to discuss your problem or might be you already have answer you can share it with me, at janderbacalso@gmail.com

**Comment by XanderDwyl** [comment]
You can use this component properties `jqStyle`

<ReactJQCloud word_array={word_list} jqStyle={ width: '100%' } />
